name: Run Tests

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
  pull_request:
    branches:
      - master
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go with Caching
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: go.sum

      - name: Install Dependencies
        working-directory: server
        run: go mod download

      - name: Run Tests
        working-directory: server
        run: make test
